-- creazione tabelle
CREATE TABLE AEROPORTO (
  id INTEGER PRIMARY KEY,
  Città TEXT NOT NULL,
  Nazione TEXT NOT NULL,
  NumeroPiste TEXT NOT NULL 
);

CREATE TABLE VOLO (
  id INTEGER PRIMARY KEY,
  IdVolo TEXT NOT NULL,
  GiornoSett TEXT NOT NULL,
  CittaPart TEXT NOT NULL,
  OraPart TEXT NOT NULL,
  CittaArr TEXT NOT NULL,
  OraArr TEXT NOT NULL,
  TipoAereo TEXT NOT NULL
);

CREATE TABLE AEREO (
    id INTEGER PRIMARY KEY,
    TipoAereo TEXT NOT NULL,
    NumPasseggeri TEXT NOT NULL,
    QtaMerci TEXT NOT NULL
    );


-- inserimento valori
INSERT INTO AEROPORTO VALUES (1, 'TORINO', 'IT','3');
INSERT INTO AEROPORTO VALUES (2, 'BOLOGNA', 'IT','2');
INSERT INTO AEROPORTO VALUES (3,'MILANO','IT','7');
INSERT INTO AEROPORTO VALUES (4,'VENEZIA','IT','2');
INSERT INTO AEROPORTO VALUES (5,'VERONA','IT','3');
INSERT INTO AEROPORTO VALUES (6,'FIRENZE','IT','4');
INSERT INTO AEROPORTO VALUES (7,'ROMA','IT','8');
INSERT INTO AEROPORTO VALUES (8,'NAPOLI','IT','5');
INSERT INTO AEROPORTO VALUES (9,'PALERMO','IT','4');
INSERT INTO AEROPORTO VALUES (10,'CAGLIARI','IT','IGNOTO');
INSERT INTO AEROPORTO VALUES (11, 'VIENNA', 'AT','3');
INSERT INTO AEROPORTO VALUES (12, 'GINEVRA', 'CH','3');
INSERT INTO AEROPORTO VALUES (13, 'BARCELLONA', 'ES','5');
INSERT INTO AEROPORTO VALUES (14, 'PRAGA', 'CZ','IGNOTO');
INSERT INTO AEROPORTO VALUES (15, 'BERLINO', 'DE','6');
INSERT INTO AEROPORTO VALUES (16, 'ISTANBUL', 'TR','7');
INSERT INTO AEROPORTO VALUES (17, 'ATENE', 'EL','6');
INSERT INTO AEROPORTO VALUES (18, 'MADRID', 'ES','5');
INSERT INTO AEROPORTO VALUES (19, 'PARIGI', 'FR','9');
INSERT INTO AEROPORTO VALUES (20, 'LISBONA', 'PT','IGNOTO');

INSERT INTO VOLO VALUES (1,'CargoDF233','Lunedì','VIENNA,','12:00:00','VERONA','13:20:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (2,'LineaGA878','Martedì','GINEVRA','09:00:00','PALERMO','10:40:00','Regional-Turboprop');
INSERT INTO VOLO VALUES (3,'LineaUJ123','Mercoledì','PARIGI','05:40:00','ROMA','07:20:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (4,'LineaPL149','Giovedì','BARCELLONA','18:00:00','VENEZIA','20:00:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (5,'LineaAZ274','Venerdì','PRAGA','14:20:00','NAPOLI','17:20:00','Wide body-Turbofan');
INSERT INTO VOLO VALUES (6,'LineaQR238','Sabato','BERLINO','02:30:00','TORINO','05:00:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (7,'LineaKD253','Domenica','ISTANBUL','11:00:00','FIRENZE','14:30:00','Wide body-Turbofan');
INSERT INTO VOLO VALUES (8,'LineaHG567','Lunedì','ATENE','13:00:00','CAGLIARI','15:30:00','Double Deck-Turbofan');
INSERT INTO VOLO VALUES (9,'CargoFT832','Martedì','MADRID','16:00:00','BOLOGNA','18:30:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (10,'LineaDR345','Mercoledì','LISBONA','17:30:00','MILANO','21:00:00','Wide body-Turbofan');
INSERT INTO VOLO VALUES (11,'CargoDF234','Lunedì','VERONA,','12:30:00','VIENNA','13:50:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (12,'LineaGA879','Martedì','PALERMO','09:30:00','GINEVRA','11:10:00','Regional-Turboprop');
INSERT INTO VOLO VALUES (13,'LineaUJ124','Mercoledì','ROMA','06:10:00','PARIGI','07:50:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (14,'LineaPL150','Giovedì','VENEZIA','18:30:00','BARCELLONA','20:30:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (15,'LineaAZ275','Venerdì','NAPOLI','14:50:00','PRAGA','17:50:00','Wide body-Turbofan');
INSERT INTO VOLO VALUES (16,'LineaQR239','Sabato','TORINO','03:00:00','BERLINO','05:30:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (17,'LineaKD254','Domenica','FIRENZE','11:30:00','ISTANBUL','15:00:00','Wide body-Turbofan');
INSERT INTO VOLO VALUES (18,'LineaHG568','Lunedì','CAGLIARI','13:30:00','ATENE','16:00:00','Double Deck-Turbofan');
INSERT INTO VOLO VALUES (19,'CargoFT833','Martedì','BOLOGNA','16:30:00','MADRID','19:00:00','Narrow body-Turboprop');
INSERT INTO VOLO VALUES (20,'LineaDR346','Mercoledì','MILANO','18:00:00','LISBONA','21:30:00','Wide body-Turbofan');

INSERT INTO AEREO VALUES (1,'BELUGA','250','50t');
INSERT INTO AEREO VALUES (2,'WIZZAIR','100','NULL');
INSERT INTO AEREO VALUES (3,'RYANAIR','200','NULL');
INSERT INTO AEREO VALUES (4,'RYANAIR','250','NULL');
INSERT INTO AEREO VALUES (5,'ALITALIA','600','NULL');
INSERT INTO AEREO VALUES (6,'RYANAIR','200','NULL');
INSERT INTO AEREO VALUES (7,'FLYEMIRATES','660','NULL');
INSERT INTO AEREO VALUES (8,'AEGEANAIRLINES','800','NULL');
INSERT INTO AEREO VALUES (9,'SPRUCEGOOSE','250','100t');
INSERT INTO AEREO VALUES (10,'ALITALIA','500','NULL');
INSERT INTO AEREO VALUES (11,'BELUGA','250','50t');
INSERT INTO AEREO VALUES (12,'WIZZAIR','100','NULL');
INSERT INTO AEREO VALUES (13,'RYANAIR','200','NULL');
INSERT INTO AEREO VALUES (14,'RYANAIR','250','NULL');
INSERT INTO AEREO VALUES (15,'ALITALIA','600','NULL');
INSERT INTO AEREO VALUES (16,'RYANAIR','200','NULL');
INSERT INTO AEREO VALUES (17,'FLYEMIRATES','660','NULL');
INSERT INTO AEREO VALUES (18,'AEGEANAIRLINES','800','NULL');
INSERT INTO AEREO VALUES (19,'SPRUCEGOOSE','250','100t');
INSERT INTO AEREO VALUES (20,'ALITALIA','500','NULL');


-- Interrogare il DataBase
SELECT Città FROM AEROPORTO WHERE NumeroPiste = 'IGNOTO';
SELECT TipoAereo FROM VOLO WHERE CittaPart = 'TORINO';
SELECT CittaPart FROM VOLO WHERE CittaArr = 'BOLOGNA';
SELECT CittaPart, CittaArr FROM VOLO WHERE IdVolo = 'LineaAZ274';